### ISSUE TITLE
(centos6) tar and lsmod not found

### ISSUE THREAD

**Issue by streetster** [neomantra/docker-onload#2]
Need to add `tar` and `module-init-tools` to the list of packages that yum is installing.

**Comment by neomantra** [comment]
I'm looking at this and your other issue.  Hopefully, it can all go in the same Dockerfile.  At worst, we can just split it into `Dockerfile.centos6` and `Dockerfile.centos7`.

Thanks for using this tooling and it's been a lonely ride ;)
