### ISSUE TITLE
OpenOnload v7.0.0.176?

### ISSUE THREAD

**Issue by holmesb** [neomantra/docker-onload#3]
A [new OpenOnload driver -  v7.0.0.176](https://support.solarflare.com/index.php/component/cognidox/?view=categories&id=361) was released in September.

The latest version in this repo is the prior one: 201811-u1.  Any chance of a new release?

**Comment by neomantra** [comment]
Thanks for your interest in this tooling! 

Historically, I have released new images the same day a new OpenOnload is released.

However, with this last release, they moved the downloads from https://openonload.org to https://support.solarflare.com

The Solarflare support site has the following [**Terms of Use**](https://solarflare.com/terms-of-service/):

• "you shall not" .... "Use any robot, spider, site search/retrieval application or other manual or automatic device or process to retrieve, index, “data mine” or in any way reproduce or circumvent the navigational structure or presentation of the Site or its contents;"

Thus, I could not take the direct download URL for that package and use it here.

I'll ping Solarflare support -- maybe they will grant me permission.

I'll post a DIY in another comment.

**Comment by neomantra** [comment]
I have attached a Bionic Dockerfile updated for their new release style.  I use it internally with my own URL.  You can build yourself like so:

```
docker build -f Dockerfile.bionic.v7.txt --build-arg ONLOAD_PACKAGE_URL="<the url>" .
```

[Dockerfile.bionic.v7.txt](https://github.com/neomantra/docker-onload/files/4160069/Dockerfile.bionic.v7.txt)

**Comment by holmesb** [comment]
Thanks @neomantra  

Doesn't strike me as very "Open".  I'll do the same.

**Comment by neomantra** [comment]
To be fair, you can still download it and look at all the source code.  As a third-party, I just don't feel like I can re-distribute it right now.  There's a similar re-distribution situation with TCPDirect (which also does not have source code, but that's their prerogative).   This tooling shows you how to do it and you are free, by their license, to do it yourself.

I've been using OpenOnload for almost a decade.  The open nature of it has definitely enhanced my customer experience.   Notably, I was a Debian/Ubuntu before it was ever supported; I was able to fix my own issues or make detailed issue reports that helped support@solarflare.com to turn-around patches(!) quickly.

**Comment by neomantra** [comment]
I've updated the Dockerfiles to allow both older and newer packaging.  I myself have a several versions in deployment so need backward compatibility.   I haven't actually tested 7.0.0.176 on host or in container.

I have a builder helper I'll commit in a bit that simplifies DIY and automated builds.

**Comment by neomantra** [comment]
I got the OK from Solarflare to include the direct download URL here.  So I've added that, tagged the release --the images built on Travis and pushed to Docker hub.
