### ISSUE TITLE
7.1.3.202

### ISSUE THREAD

**Issue by tolga-talkme** [neomantra/docker-onload#8]
Are there any plan for the new release (7.1.3.202) ?

**Comment by neomantra** [comment]
Thanks for the ping -- I hadn't upgraded our systems yet so hadn't addressed it.  But knowing somebody cares is a motivator ;)   Going through CI/CD now

**Comment by neomantra** [comment]
Released as tag `7.1.3.202` so images named like `neomantra/onload:7.1.3.202-focal`
